const post: IPost = {
  title: 'Privacy Policy - Kick the Prince: Princess Rush',
  createdAt: 'July 31, 2017',
  content: `
# Privacy Policy

At Limesociety Co., Ltd (Republic of Korea Business Number: 220-88-32405) (defined here as 'We' or 'Our'), We value your comments, suggestions and feedback. Our Privacy Policy sets out how we collect, use and disclose "personal information" and other "non-personal information" we have gathered about you.

This policy will let you know:

- What information is collected from you;
- How your information is used;
- With whom your information may be shared.

We are bound by the Korean Privacy Act 2017 (Cth) ("Act") regarding the manner in which We handle your personal information and how We respond to your requests to access and correct it. We also adhere to the principles enshrined in the US Privacy Act (1974) ("US Act") and the principles contained in the Children's Online Privacy Protection Act ("COPPA").

We will comply with all relevant legislative requirements, and, in the event of any inconsistency, the legislative requirements will override the provisions of this document.

## Third Party Advertising

Advertisements from third party ad networks may be displayed in our Games from time to time. All reasonable endeavours are used to ensure that these ad networks comply with the Act, the US Act, and COPPA in the provision of their services towards us.

If you click on any advertisements through Our game, the advertisers may use cookies and other web-tracking technologies to collect data. Some of this may be personal information, and some of it non-personal information. We recommend that you review the terms of use and privacy policy for any advertiser with whom you are interacting before doing so.

The list of our ad networks privacy policies may be found here:

- Unity Ads: https://unity3d.com/legal/privacy-policy

## Collection of other 'Non-Personal' Information

Some non-personal information may be gathered while you use Our games. Non personal information is general, non-identifiable and anonymous information that is gathered for statistical, analytical and research purposes such as the improvement of our games (for example, bug fixes).

Though We do not use cookies in order to track your movement around the web, Our websites (https://limesociety.com) use Google Analytics to help analyse how users use these sites. The tool uses cookies to collect internet log information and general visitor behaviour information in an anonymous form. The information generated by the cookie about your use of the website, including your IP address, is transmitted to Google. This information is then used to evaluate use of our website and to compile statistical reports on website activity.

The Google Analytics privacy policy can be found here:

- Google Analytics: http://www.google.com/analytics/learn/privacy.html

## Policy Updates

This Policy may change from time to time. The most current version of our Privacy Policy can be found at https://limesociety.com/blog/5. We will always keep this up to date so that you know what information we will collect from you, how we may use it, and when we may disclose it.

## Complaints

You can lodge a complaint with us about any breach of our Privacy Policy at the address below.

## Privacy Policy Contact Information

If you have any questions about our Privacy Policy, please contact us at:

E: privacy@limesociety.com

## Privacy policy last updated July 2017
`
}

export default post
